// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mud.proto

package mud

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Action_Type int32

const (
	Action_SAY   Action_Type = 0
	Action_EMOTE Action_Type = 1
	Action_LOOK  Action_Type = 2
)

var Action_Type_name = map[int32]string{
	0: "SAY",
	1: "EMOTE",
	2: "LOOK",
}

var Action_Type_value = map[string]int32{
	"SAY":   0,
	"EMOTE": 1,
	"LOOK":  2,
}

func (x Action_Type) String() string {
	return proto.EnumName(Action_Type_name, int32(x))
}

func (Action_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_332afdaf9af33408, []int{3, 0}
}

type Message struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_332afdaf9af33408, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Token struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Expires              string   `protobuf:"bytes,2,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_332afdaf9af33408, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Token) GetExpires() string {
	if m != nil {
		return m.Expires
	}
	return ""
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_332afdaf9af33408, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Action struct {
	Action               Action_Type `protobuf:"varint,1,opt,name=action,proto3,enum=mud.Action_Type" json:"action,omitempty"`
	Argument             []string    `protobuf:"bytes,2,rep,name=argument,proto3" json:"argument,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_332afdaf9af33408, []int{3}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetAction() Action_Type {
	if m != nil {
		return m.Action
	}
	return Action_SAY
}

func (m *Action) GetArgument() []string {
	if m != nil {
		return m.Argument
	}
	return nil
}

type Player struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Username             string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Logins               uint64               `protobuf:"varint,5,opt,name=logins,proto3" json:"logins,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	LastLogin            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_332afdaf9af33408, []int{4}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Player) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Player) GetLogins() uint64 {
	if m != nil {
		return m.Logins
	}
	return 0
}

func (m *Player) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Player) GetLastLogin() *timestamp.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func init() {
	proto.RegisterEnum("mud.Action_Type", Action_Type_name, Action_Type_value)
	proto.RegisterType((*Message)(nil), "mud.Message")
	proto.RegisterType((*Token)(nil), "mud.Token")
	proto.RegisterType((*LoginRequest)(nil), "mud.LoginRequest")
	proto.RegisterType((*Action)(nil), "mud.Action")
	proto.RegisterType((*Player)(nil), "mud.Player")
}

func init() { proto.RegisterFile("mud.proto", fileDescriptor_332afdaf9af33408) }

var fileDescriptor_332afdaf9af33408 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x3d, 0x8f, 0xd3, 0x40,
	0x10, 0xcd, 0x26, 0xfe, 0xb8, 0x4c, 0x4e, 0x28, 0x4c, 0x81, 0x2c, 0x37, 0x58, 0x06, 0x09, 0x57,
	0x3e, 0x14, 0xa0, 0xa0, 0x3c, 0xa1, 0x83, 0x82, 0x3b, 0x05, 0x4c, 0x1a, 0x2a, 0xb4, 0x17, 0x0f,
	0xc6, 0x22, 0xfe, 0xc0, 0xbb, 0x2b, 0xb8, 0x9a, 0x1f, 0x4d, 0x8b, 0x76, 0xd6, 0x8e, 0x02, 0x42,
	0xa2, 0x9b, 0xf7, 0xe6, 0xcd, 0xec, 0xcc, 0xbc, 0x85, 0x65, 0x63, 0xca, 0xbc, 0x1f, 0x3a, 0xdd,
	0xe1, 0xa2, 0x31, 0x65, 0xfc, 0xb0, 0xea, 0xba, 0xea, 0x40, 0x17, 0x4c, 0xdd, 0x9a, 0xcf, 0x17,
	0xba, 0x6e, 0x48, 0x69, 0xd9, 0xf4, 0x4e, 0x95, 0x3e, 0x82, 0xf0, 0x86, 0x94, 0x92, 0x15, 0x61,
	0x04, 0x61, 0xe3, 0xc2, 0x48, 0x24, 0x22, 0x5b, 0x16, 0x13, 0x4c, 0x5f, 0x80, 0xbf, 0xeb, 0xbe,
	0x52, 0x8b, 0x08, 0x9e, 0x31, 0x75, 0x39, 0xe6, 0x39, 0xb6, 0x65, 0xf4, 0xa3, 0xaf, 0x07, 0x52,
	0xd1, 0xdc, 0x95, 0x8d, 0x30, 0x7d, 0x0d, 0xe7, 0xd7, 0x5d, 0x55, 0xb7, 0x05, 0x7d, 0x33, 0xa4,
	0x34, 0xc6, 0x70, 0x66, 0x14, 0x0d, 0xad, 0x6c, 0xa6, 0x17, 0x8e, 0xd8, 0xe6, 0x7a, 0xa9, 0xd4,
	0xf7, 0x6e, 0x28, 0xc7, 0x36, 0x47, 0x9c, 0x6a, 0x08, 0x2e, 0xf7, 0xba, 0xee, 0x5a, 0xcc, 0x20,
	0x90, 0x1c, 0x71, 0xfd, 0xbd, 0xcd, 0x3a, 0xb7, 0xfb, 0xba, 0x64, 0xbe, 0xbb, 0xeb, 0xa9, 0x18,
	0xf3, 0xb6, 0x9f, 0x1c, 0x2a, 0xd3, 0x50, 0xab, 0xa3, 0x79, 0xb2, 0xb0, 0xfd, 0x26, 0x9c, 0x3e,
	0x06, 0xcf, 0x6a, 0x31, 0x84, 0xc5, 0x87, 0xcb, 0x8f, 0xeb, 0x19, 0x2e, 0xc1, 0xbf, 0xba, 0xd9,
	0xee, 0xae, 0xd6, 0x02, 0xcf, 0xc0, 0xbb, 0xde, 0x6e, 0xdf, 0xae, 0xe7, 0xe9, 0x2f, 0x01, 0xc1,
	0xbb, 0x83, 0xbc, 0xa3, 0xe1, 0x9f, 0x6b, 0x9f, 0x2e, 0x33, 0xff, 0x6b, 0x19, 0x04, 0x8f, 0xf9,
	0x85, 0xd3, 0x33, 0x97, 0xc0, 0xaa, 0x24, 0xb5, 0x1f, 0xea, 0x9e, 0xe7, 0xf7, 0x38, 0x75, 0x4a,
	0xe1, 0x03, 0x08, 0x0e, 0xf6, 0x5c, 0x2a, 0xf2, 0x13, 0x91, 0x79, 0xc5, 0x88, 0xf0, 0x39, 0x84,
	0xfb, 0x81, 0xa4, 0xa6, 0x32, 0x0a, 0x12, 0x91, 0xad, 0x36, 0x71, 0xee, 0x5c, 0xcd, 0x27, 0x57,
	0xf3, 0xdd, 0xe4, 0x6a, 0x31, 0x49, 0xf1, 0x25, 0xc0, 0x41, 0x2a, 0xfd, 0x89, 0x9b, 0x44, 0xe1,
	0x7f, 0x0b, 0x97, 0x56, 0xcd, 0x76, 0x6d, 0x7e, 0x0a, 0xf0, 0xde, 0xd8, 0x99, 0x33, 0xf0, 0x99,
	0xc1, 0xfb, 0x7c, 0xe7, 0x53, 0x33, 0x63, 0x60, 0x8a, 0xbf, 0x45, 0x3a, 0xc3, 0x0c, 0xbc, 0x57,
	0x5f, 0xa4, 0xc6, 0x73, 0x66, 0xc7, 0x1f, 0x15, 0xff, 0x81, 0xd2, 0x59, 0x26, 0x9e, 0x0a, 0x7c,
	0x02, 0xfe, 0x7b, 0x43, 0x86, 0x70, 0x75, 0xe2, 0x5d, 0xec, 0x80, 0x3b, 0xb7, 0x13, 0xde, 0x06,
	0x3c, 0xe4, 0xb3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xc7, 0x35, 0x5d, 0xd3, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Token, error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (Game_ChatClient, error)
	Queue(ctx context.Context, opts ...grpc.CallOption) (Game_QueueClient, error)
}

type gameClient struct {
	cc *grpc.ClientConn
}

func NewGameClient(cc *grpc.ClientConn) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/mud.Game/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) Chat(ctx context.Context, opts ...grpc.CallOption) (Game_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Game_serviceDesc.Streams[0], "/mud.Game/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameChatClient{stream}
	return x, nil
}

type Game_ChatClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type gameChatClient struct {
	grpc.ClientStream
}

func (x *gameChatClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameChatClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameClient) Queue(ctx context.Context, opts ...grpc.CallOption) (Game_QueueClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Game_serviceDesc.Streams[1], "/mud.Game/Queue", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameQueueClient{stream}
	return x, nil
}

type Game_QueueClient interface {
	Send(*Action) error
	Recv() (*Player, error)
	grpc.ClientStream
}

type gameQueueClient struct {
	grpc.ClientStream
}

func (x *gameQueueClient) Send(m *Action) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameQueueClient) Recv() (*Player, error) {
	m := new(Player)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameServer is the server API for Game service.
type GameServer interface {
	Login(context.Context, *LoginRequest) (*Token, error)
	Chat(Game_ChatServer) error
	Queue(Game_QueueServer) error
}

func RegisterGameServer(s *grpc.Server, srv GameServer) {
	s.RegisterService(&_Game_serviceDesc, srv)
}

func _Game_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mud.Game/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServer).Chat(&gameChatServer{stream})
}

type Game_ChatServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type gameChatServer struct {
	grpc.ServerStream
}

func (x *gameChatServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameChatServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Game_Queue_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServer).Queue(&gameQueueServer{stream})
}

type Game_QueueServer interface {
	Send(*Player) error
	Recv() (*Action, error)
	grpc.ServerStream
}

type gameQueueServer struct {
	grpc.ServerStream
}

func (x *gameQueueServer) Send(m *Player) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameQueueServer) Recv() (*Action, error) {
	m := new(Action)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Game_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mud.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Game_Login_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _Game_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Queue",
			Handler:       _Game_Queue_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mud.proto",
}
