name: dart
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Jacob Dearing <jacob@dearing.io>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  async: '>=1.13.3 <3.0.0'
  grpc: ^0.6.5
  protobuf: ^0.10.4
  googleapis_auth: ^0.2.3+6
  
dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
